version: '3'
services:
  redis:
    image: 'redis:latest'
    ports:
      - '127.0.0.1:6379:6379/tcp'
    healthcheck:
      test: redis-cli ping
      interval: 3s
      timeout: 5s
      retries: 5

  redisinsight:
    image: 'redislabs/redisinsight:latest'
    ports:
      - '127.0.0.1:8001:8001'